# Run in R: source("C:/Users/stjuk/Documents/GitHub/J-Ratings/scripts/EuropeanFootball/rebuild_denmark_sources.R")
# Preview only: Sys.setenv(DENMARK_REBUILD_DRY_RUN="1")
rebuild_denmark_sources <- function() {
  root<-normalizePath(Sys.getenv("J_RATINGS_REPO","C:/Users/stjuk/Documents/GitHub/J-Ratings"),winslash="/",mustWork=TRUE)
  for(p in c("data.table","nanoparquet")) if(!requireNamespace(p,quietly=TRUE))stop("Install required package: ",p)
  source(file.path(root,"scripts/EuropeanFootball/denmark_source_rebuild.R"),local=TRUE)
  base<-file.path(root,"EuropeanFootball/pipeline_data")
  master<-file.path(base,"Matches_Clean_Combined/european_football_all_matches.csv")
  existing<-data.table::fread(master)
  replacement<-build_denmark_sources(root)
  updated<-replace_denmark_sources(existing,replacement)
  cat("Replacing ",sum(existing$Country=="Denmark" & existing$CompetitionType=="league" & existing$Tier==1L,na.rm=TRUE)," Denmark league matches with ",nrow(replacement)," approved-source matches.\n",sep="")
  print(replacement[,.(Matches=.N,FirstDate=min(Date),LastDate=max(Date)),by=Source])
  report<-file.path(base,"Audit/denmark_source_rebuild")
  data.table::fwrite(replacement,file.path(report,"replacement_matches.csv"))
  if(Sys.getenv("DENMARK_REBUILD_DRY_RUN","0")=="1") {cat("Preview complete; live input, ratings and website unchanged.\n");return(invisible(updated))}
  backup<-tempfile(pattern=paste0("backup_",format(Sys.time(),"%Y%m%d_%H%M%S"),"_"),tmpdir=report)
  if(!dir.create(backup))stop("Cannot create backup directory")
  files<-c(master,list.files(file.path(base,"Elo"),full.names=TRUE))
  files<-files[!file.info(files)$isdir]
  for(f in files)if(!file.copy(f,file.path(backup,basename(f))))stop("Backup failed: ",f)
  marker<-file.path(base,"Elo/rebuild_required.txt")
  # This marker disables the frozen checkpoint even if a rebuild is interrupted.
  writeLines("Denmark historical source replacement requires a full Elo rebuild.",marker)
  staged<-file.path(backup,"replacement_master.csv");data.table::fwrite(updated,staged,na="")
  if(!file.copy(staged,master,overwrite=TRUE))stop("Cannot replace master; backups: ",backup)
  writeLines("OpenFootball top flight from 2023; Schochastics before 2023; old Denmark rows excluded.",file.path(base,"Reference/denmark_source_policy.txt"))
  cat("Backups: ",backup,"\nRebuilding all Club Football ratings and website data; this can take some time.\n",sep="")
  previous<-Sys.getenv("J_RATINGS_REPO",unset=NA_character_)
  on.exit(if(is.na(previous))Sys.unsetenv("J_RATINGS_REPO") else Sys.setenv(J_RATINGS_REPO=previous),add=TRUE)
  Sys.setenv(J_RATINGS_REPO=root)
  source(file.path(root,"scripts/EuropeanFootball/02_calculate_elo.R"),local=new.env(parent=globalenv()))
  source(file.path(root,"scripts/EuropeanFootball/03_write_json.R"),local=new.env(parent=globalenv()))
  cat("Denmark source replacement and website rebuild complete. Coverage report: ",file.path(report,"coverage.csv"),"\n",sep="")
}
rebuild_denmark_sources()
